<?php 
return array (
  'ADMIN_SUPER_ROLE' => '5',
  'ADMIN_MARKET_ROLE' => '10,3,28',
  'ADMIN_EDUCATIONAL_ROLE' => '32',
  'ADMIN_SERVICE_ROLE' => 2,
  'ADMIN_USER_MAX_DISCOUNT' => '3000',
  'SMSHINT_USER' => '160203',
);